baseURL = 'http://localhost:63342/DELTA/deltav/deltav/public/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme="deltavtheme"


[menu]
  [[menu.main]]
    name = "Inicio"
    pre = "inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Proyectos"
    pre = "proyectos"
    url = "/proyectos/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
     name = "Revista"
     pre = "revista"
     url = "/revistas/"
     weight = 4
  [[menu.main]]
      name = "Nosotros"
      pre = "nosotros"
      url = "/nosotros/index.html"
      weight = 5