baseURL = 'https://www.deltavudea.com/'
languageCode = 'es-BO'
title = 'DeltaV'
theme = "deltavtheme"

magazineImagesPath = "images/PNG-Dobles"
relativeURLs = true
[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[menu]
    [[menu.main]]
        name = "Inicio"
        identifier = "inicio"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Proyectos"
        identifier = "proyectos"
        url = "/proyectos/"
        weight = 2

    [[menu.main]]
        name = "Wiki"
        identifier = "wiki"
        url = "/wiki/"
        weight = 3

    [[menu.main]]
        name = "Revista"
        identifier = "revista"
        url = "/revistas/"
        weight = 5

    [[menu.main]]
        name = "Nosotros"
        identifier = "nosotros"
        url = "/nosotros/index.html"
        weight = 6

    [[menu.main]]
        name = "Support us"
        identifier = "support us"
        url = "https://www.patreon.com/deltavudea"
        weight = 6
